version: '3'

services:
  # DB
  recipes-database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgress
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
      POSTGRES_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # DB Visualizer
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
# Server
  recipes-api:
    container_name: recipes-api
    build: 
      context: .
      dockerfile: .docker/rest-api.dev.dockerfile
    ports:
      - 3001:3001
volumes:
  db-storage:
