version: '3'

services:
  # DB
  recipes-database:
    image: postgres:latest
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgress"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_DB: postgress
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
      POSTGRES_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-storage:/var/lib/postgresql/data
    networks:
      - database
    ports:
      - "5432:5432"
  # DB Visualizer
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - recipes-database
    networks:
      - database
  # Server
  recipes-api:
    container_name: recipes-api
    build:
      context: .
      dockerfile: .docker/rest-api.dev.dockerfile
    # volumes:
    #   - ./libraries:/app/libraries
    #   - ./apps/recipes-rest:/app/apps/recipes-rest 
    ports:
      - 3001:3001
    depends_on:
      - recipes-database
    networks:
      - database
volumes:
  db-storage:

networks:
  client:
  database:
