version: '3'

services:
  # DB
  recipes-database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  # DB Visualizer
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
# Server
  recipes-api:
    container_name: recipes-api
    build: 
      context: .
      dockerfile: .docker/rest-api.dev.dockerfile
volumes:
  db-storage:
